/**
 * Evidence bundles — a portable export of everything the project holds about
 * one target, plus a handoff an AI agent can pick the work up from.
 *
 * Two things leave the machine here that never did before, so both are stated
 * rather than implied:
 *
 *  - A bundle is **redacted by default**. Captured traffic is kept verbatim in
 *    the project (that is the point of a proxy), but a bundle is a *derived*
 *    artifact that gets mailed to a triager, dropped in a ticket, or pasted
 *    into a model. `SECURITY.md` already draws that line for logs and findings;
 *    bundles sit on the same side of it. Raw captures are an explicit opt-in
 *    and are recorded in the manifest and the audit log.
 *  - A handoff is **not an authorization**. It carries the scope the engine
 *    enforces so an agent reading it can see what is permitted, but no text in
 *    a handoff widens anything: the fail-closed gate is still the only thing
 *    that decides whether a request is allowed to leave.
 */

import type { Confidence, Severity } from './findings.js';

export interface EvidenceBundleOptions {
  /**
   * Write captured headers and bodies as they were seen instead of redacting
   * them. Off by default. Turning it on puts live cookies, tokens and PII in a
   * file designed to be shared — do it deliberately, for a triager who needs
   * the exact bytes, and treat the bundle as a secret afterwards.
   */
  includeRawCaptures?: boolean;
  /** Newest-first cap on exchanges written. Default 500. */
  maxExchanges?: number;
  /** Include the in-memory log tail as `logs/tacnoc.log.jsonl`. Default true. */
  includeLogs?: boolean;
  /** Include `HANDOFF.md` + `handoff.json`. Default true. */
  includeHandoff?: boolean;
}

export interface EvidenceBundleSummary {
  path: string;
  host: string;
  generatedAt: number;
  sizeBytes: number;
  /** SHA-256 of the bundle as written — the integrity check for the recipient. */
  sha256: string;
  exchangeCount: number;
  /** Exchanges the host actually has, before `maxExchanges` was applied. */
  exchangesAvailable: number;
  findingCount: number;
  auditCount: number;
  logCount: number;
  /** False when `includeRawCaptures` was set. */
  redacted: boolean;
  entries: string[];
}

export interface LogExportSummary {
  path: string;
  generatedAt: number;
  sizeBytes: number;
  sha256: string;
  recordCount: number;
  /** Records the ring buffer discarded before this export. */
  droppedCount: number;
}

/** Who the engagement is with, and what the gate will actually permit. */
export interface AgentHandoffAuthorization {
  program?: string;
  platform?: string;
  handle?: string;
  authorizationRef?: string;
  /** Enabled include rules, rendered as `match: host`. */
  inScope: string[];
  /** Enabled exclude rules, same rendering. These veto. */
  outOfScope: string[];
  /**
   * True when no enabled include rule exists, so the engine would refuse every
   * request. An agent that sees this must stop and say so, not work around it.
   */
  failClosed: boolean;
  /** Whether this bundle's target is itself in scope right now. */
  targetInScope: boolean;
}

export interface AgentHandoffEndpoint {
  path: string;
  methods: string[];
  statusCodes: number[];
  parameterNames: string[];
  requestCount: number;
  latestExchangeId: string;
  inScope: boolean;
}

export interface AgentHandoffFinding {
  id: string;
  title: string;
  severity: Severity;
  confidence: Confidence;
  module: string;
  exchangeId: string;
  suppressed: boolean;
  /** Bundle-relative path to the exchange this came from, when it is included. */
  evidenceFile?: string;
}

export interface AgentHandoffEvidenceEntry {
  file: string;
  kind: 'exchange' | 'findings' | 'audit' | 'log' | 'engagement' | 'manifest';
  describes: string;
}

/**
 * The machine-readable half of the handoff. `HANDOFF.md` renders the same
 * facts; neither is generated by a model — every field is read from the
 * project, so a handoff cannot assert something the engine does not hold.
 */
export interface AgentHandoff {
  schemaVersion: 1;
  generatedAt: number;
  tool: { name: 'TACNOC'; version: string };
  /** Mirrors the bundle: false means raw captures are present. */
  redacted: boolean;
  authorization: AgentHandoffAuthorization;
  target: {
    host: string;
    origins: string[];
    endpoints: AgentHandoffEndpoint[];
    exchangeCount: number;
    firstSeen?: number;
    lastSeen?: number;
  };
  findings: AgentHandoffFinding[];
  evidence: AgentHandoffEvidenceEntry[];
  /** `session.engineBriefing()` — deterministic, no model involved. */
  engineBriefing: string;
  /** Actions already taken against this target, from the audit log. */
  alreadyTried: string[];
  /** Things the evidence raises and does not answer. */
  openQuestions: string[];
  /** Rules of engagement. These bind the agent; they are not advisory. */
  constraints: string[];
  /** A starting objective, phrased for `startMeshRun`. */
  suggestedObjective: string;
}

/** What a live handoff did, so the UI can say it rather than imply it. */
export interface AgentHandoffResult {
  host: string;
  objective: string;
  runId: string;
  handoff: AgentHandoff;
}
