/**
 * Canonical HTTP message model.
 *
 * Design goals (see ARCHITECTURE.md / THREAT_MODEL.md):
 *  - Preserve BOTH the raw bytes and a parsed representation. We never silently
 *    lose or mutate captured bytes.
 *  - Preserve header ORDER, original CASING, and DUPLICATES. HTTP semantics and
 *    many security findings depend on these, so headers are an ordered list of
 *    {name,value}, not a map.
 *  - Large bodies are represented by a reference to an on-disk blob so they are
 *    never forced to live entirely in memory.
 *
 * This module is pure data + pure helpers. It has no I/O and no Node-only
 * dependencies beyond types, so it is safe to import from the renderer as well.
 */

export type Scheme = 'http' | 'https';

export type MessageSource = 'proxy' | 'repeater' | 'variation' | 'import';

/** A single header line. Never deduplicated or reordered on capture. */
export interface HttpHeader {
  name: string;
  value: string;
}

/**
 * The body of a request or response.
 *
 * `inline` holds small bodies directly. `blobId` references the content-
 * addressed blob store for larger bodies. Exactly one of `inline`/`blobId` is
 * set for a non-empty body; both are absent for an empty body.
 */
export interface MessageBody {
  /** Number of raw bytes actually captured (after any truncation). */
  size: number;
  /** True if capture hit the configured max-body limit and stopped early. */
  truncated: boolean;
  /** `Content-Encoding` observed on the wire (e.g. "gzip"), if any. */
  contentEncoding?: string;
  /** Content-addressed id in the blob store, when spilled to disk. */
  blobId?: string;
  /** In-memory bytes for small bodies. */
  inline?: Uint8Array;
}

export const EMPTY_BODY: MessageBody = Object.freeze({ size: 0, truncated: false });

export interface CapturedRequest {
  method: string;
  /** The request-target exactly as received (origin-form path or absolute-form URI). */
  target: string;
  /** Fully-qualified absolute URL reconstructed from target + host + scheme. */
  url: string;
  httpVersion: string;
  headers: HttpHeader[];
  body: MessageBody;
}

export interface CapturedResponse {
  statusCode: number;
  statusMessage: string;
  httpVersion: string;
  headers: HttpHeader[];
  body: MessageBody;
}

export interface ExchangeTiming {
  /** Epoch ms when the request left the proxy toward the origin. */
  startedAt: number;
  /** Milliseconds to first response byte. */
  ttfbMs?: number;
  /** Milliseconds for the full response. */
  durationMs?: number;
}

/**
 * A complete request/response pair as stored in history. `response` is absent
 * for dropped, in-flight, or errored exchanges.
 */
export interface HttpExchange {
  id: string;
  createdAt: number;
  source: MessageSource;
  scheme: Scheme;
  host: string;
  port: number;
  inScope: boolean;
  request: CapturedRequest;
  response?: CapturedResponse;
  timing?: ExchangeTiming;
  /** True when generated by an automated tool (e.g. the variation engine). */
  automated: boolean;
  /** Variation/automation job id, when applicable. */
  jobId?: string;
  notes?: string;
  tags: string[];
  /** Populated when the origin/connection errored instead of responding. */
  error?: string;
}

// ---------------------------------------------------------------------------
// Header helpers (case-insensitive, duplicate-aware)
// ---------------------------------------------------------------------------

/** Return the first header value matching `name` (case-insensitive), or undefined. */
export function getHeader(headers: readonly HttpHeader[], name: string): string | undefined {
  const lower = name.toLowerCase();
  for (const h of headers) {
    if (h.name.toLowerCase() === lower) return h.value;
  }
  return undefined;
}

/** Return every value for `name` (case-insensitive), preserving order. */
export function getHeaders(headers: readonly HttpHeader[], name: string): string[] {
  const lower = name.toLowerCase();
  const out: string[] = [];
  for (const h of headers) {
    if (h.name.toLowerCase() === lower) out.push(h.value);
  }
  return out;
}

export function hasHeader(headers: readonly HttpHeader[], name: string): boolean {
  return getHeader(headers, name) !== undefined;
}

/**
 * Build the header block ("Name: value\r\n" lines) preserving original order,
 * casing, and duplicates. Does not include the terminating blank line.
 */
export function serializeHeaders(headers: readonly HttpHeader[]): string {
  return headers.map((h) => `${h.name}: ${h.value}`).join('\r\n');
}

/**
 * Convert Node's flat `rawHeaders` array (["Name","value","Name2","value2",...])
 * into ordered, casing- and duplicate-preserving HttpHeader[].
 */
export function fromRawHeaders(raw: readonly string[]): HttpHeader[] {
  const out: HttpHeader[] = [];
  for (let i = 0; i + 1 < raw.length; i += 2) {
    out.push({ name: raw[i] as string, value: raw[i + 1] as string });
  }
  return out;
}

/** Parse the MIME type (without parameters) from a Content-Type value. */
export function mimeType(headers: readonly HttpHeader[]): string | undefined {
  const ct = getHeader(headers, 'content-type');
  if (!ct) return undefined;
  const semi = ct.indexOf(';');
  return (semi === -1 ? ct : ct.slice(0, semi)).trim().toLowerCase();
}

/**
 * Reconstruct the raw request-line + headers block for a request. The body is
 * appended separately by callers that have the bytes. Uses the exact captured
 * target and header lines so the raw view is faithful.
 */
export function serializeRequestHead(req: CapturedRequest): string {
  const requestLine = `${req.method} ${req.target} ${req.httpVersion}`;
  return `${requestLine}\r\n${serializeHeaders(req.headers)}\r\n\r\n`;
}

export function serializeResponseHead(res: CapturedResponse): string {
  const statusLine = `${res.httpVersion} ${res.statusCode} ${res.statusMessage}`;
  return `${statusLine}\r\n${serializeHeaders(res.headers)}\r\n\r\n`;
}

/** Default non-privileged host/port used across the app. */
export const DEFAULT_PROXY_HOST = '127.0.0.1';
export const DEFAULT_PROXY_PORT = 8080;
