#!/usr/bin/env node
/**
 * Generate the brand artifacts from ONE source of truth:
 * `src/renderer/public/owl.svg` — the GreyNOC owl.
 *
 *   1. `src/renderer/src/components/OwlMark.tsx` — the owl inlined as a React
 *      SVG element. Inlined rather than loaded as a file so it inherits
 *      `currentColor` (it has to read on both the dark and the light theme) and
 *      so it asks nothing of `img-src`: the renderer runs under a strict CSP.
 *   2. `build/icon.png` — the 1024x1024 application icon electron-builder
 *      converts into the per-platform icons (.ico / .icns).
 *
 * Both outputs are COMMITTED, so a normal build and a normal checkout need
 * neither this script nor a headless browser. Re-run it only when the owl
 * changes:  npm run brand
 *
 * The icon is rendered with the Playwright Chromium already present for the E2E
 * suite, so this adds no dependency.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import * as path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE = path.join(root, 'src/renderer/public/owl.svg');
const COMPONENT = path.join(root, 'src/renderer/src/components/OwlMark.tsx');
const ICON = path.join(root, 'build/icon.png');
/** Packaged copy for the BrowserWindow icon — Windows and macOS take theirs
 * from the executable/bundle, but Linux and `electron-vite dev` need a file. */
const WINDOW_ICON = path.join(root, 'src/renderer/public/icon.png');

/** The app's dark surface (`--bg` in styles.css) — the icon badge matches it. */
const BADGE = '#0d1117';
const ICON_SIZE = 1024;
const WINDOW_ICON_SIZE = 256;
/** Owl height as a fraction of the canvas; the rest is the badge's margin. */
const OWL_SCALE = 0.62;

const svg = readFileSync(SOURCE, 'utf8');

const viewBox = /viewBox="([^"]+)"/.exec(svg)?.[1];
const d = /<path[^>]*\sd="([^"]+)"/.exec(svg)?.[1];
if (!viewBox || !d) {
  console.error(`Could not read a viewBox and a single path from ${SOURCE}.`);
  process.exit(1);
}

// ---------------------------------------------------------------- component

const component = `/**
 * The GreyNOC owl — the application's brand mark.
 *
 * GENERATED by scripts/generate-brand.mjs from src/renderer/public/owl.svg.
 * Edit the SVG and re-run \`npm run brand\`; do not hand-edit this file.
 *
 * The owl is inlined as an SVG element rather than referenced as an image so it
 * takes its colour from \`currentColor\` — it has to read correctly on both the
 * dark and the light theme — and so it needs nothing from \`img-src\` under the
 * renderer's strict CSP.
 */
import React from 'react';

const OWL_VIEW_BOX = '${viewBox}';

const OWL_PATH =
  '${d}';

export function OwlMark({
  className,
  title,
}: {
  className?: string;
  /** Give a title only where the owl carries meaning; elsewhere it is decoration. */
  title?: string;
}): JSX.Element {
  return (
    <svg
      className={className}
      viewBox={OWL_VIEW_BOX}
      fill="none"
      role={title ? 'img' : undefined}
      aria-label={title}
      aria-hidden={title ? undefined : true}
    >
      <path fill="currentColor" fillRule="evenodd" d={OWL_PATH} />
    </svg>
  );
}
`;

mkdirSync(path.dirname(COMPONENT), { recursive: true });
writeFileSync(COMPONENT, component, 'utf8');
console.log(`Wrote ${path.relative(root, COMPONENT)} (${component.length} bytes).`);

// --------------------------------------------------------------------- icon

const [, , vbW, vbH] = viewBox.split(/\s+/).map(Number);

/** The badge at a given edge length. Every dimension is derived from `size`,
 *  so the owl keeps its proportions at 1024 and at 256 alike. */
function badgeHtml(size) {
  const owlH = size * OWL_SCALE;
  const owlW = (owlH * vbW) / vbH;
  return `<!doctype html><meta charset="utf-8">
<style>
  html,body { margin:0; width:${size}px; height:${size}px; background:transparent; }
  .badge {
    width:${size}px; height:${size}px; border-radius:50%;
    background:${BADGE}; display:grid; place-items:center;
  }
  svg { width:${owlW}px; height:${owlH}px; color:#ffffff; display:block; }
</style>
<div class="badge">
  <svg viewBox="${viewBox}" fill="none"><path fill="currentColor" fill-rule="evenodd" d="${d}"/></svg>
</div>`;
}

const { chromium } = await import('playwright');
const browser = await chromium.launch();
try {
  for (const [file, size] of [
    [ICON, ICON_SIZE],
    [WINDOW_ICON, WINDOW_ICON_SIZE],
  ]) {
    const p = await browser.newPage({
      viewport: { width: size, height: size },
      deviceScaleFactor: 1,
    });
    await p.setContent(badgeHtml(size));
    mkdirSync(path.dirname(file), { recursive: true });
    // omitBackground keeps the square outside the circle transparent.
    await p.screenshot({ path: file, omitBackground: true });
    await p.close();
    console.log(`Wrote ${path.relative(root, file)} (${size}x${size}).`);
  }
} finally {
  await browser.close();
}
